# USDA_MAP ฉบับรวมสมบูรณ์ (ครอบคลุมทั้ง 3 รอบการอัปเดต)
USDA_MAP = {
    # --- กลุ่มเนื้อสัตว์ ---
    'เนื้อหมู': 'Pork, fresh, loin, tenderloin, separable lean only, raw',
    'หมูสับ': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'หมูปนมัน': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'หมูเนื้อปนมัน': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'เนื้อหมูสับ': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'เนื้อหมูสับละเอียด': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'หมูสามชั้น': 'Pork, fresh, belly, raw',
    'มันหมู': 'Pork, fresh, backfat, raw',
    'มันหมูแข็ง': 'Pork, fresh, backfat, raw',
    'มันหมูหั่นละเอียด': 'Pork, fresh, backfat, raw',
    'มันหมูต้มสุกหั่น': 'Pork, fresh, backfat, cooked',
    'น้ำมันหมู': 'Lard',
    'หนังหมู': 'Pork, fresh, variety meats and by-products, stomach, raw',
    'หนังหมูต้มหั่นฝอย': 'Pork, fresh, variety meats and by-products, stomach, cooked, simmered',
    'หนังหมูต้มสุกหั่นฝอย': 'Pork, fresh, variety meats and by-products, stomach, cooked, simmered',
    'ไส้หมู': 'Pork, fresh, variety meats and by-products, chitterlings, raw',
    'ตับหมู': 'Pork, fresh, variety meats and by-products, liver, raw',
    'ตับหมูสับ': 'Pork, fresh, variety meats and by-products, liver, raw',
    'ตับหมูบดละเอียด': 'Pork, fresh, variety meats and by-products, liver, raw',
    'ตับหมูสับละเอียด': 'Pork, fresh, variety meats and by-products, liver, raw',
    'หมูหั่นแล้ว': 'Pork, fresh, loin, tenderloin, separable lean only, raw',
    'หมูเด้งสำเร็จรูป': 'Pork, ground, 72% lean meat / 28% fat, raw',
    'หมูแฮม': 'Pork, cured, ham, boneless, extra lean and regular, unheated',
    'หมูแฮมสับละเอียด': 'Pork, cured, ham, boneless, extra lean and regular, unheated',
    'กุนเชียง': 'Sausage, Chinese, pork',
    'ไส้กรอก': 'Sausage, pork, fresh, bulk',
    'ไส้กรอกหมูแห้ง': 'Sausage, Chinese, pork',

    'เนื้อโค': 'Beef, flank, separable lean and fat, trimmed to 0" fat, all grades, raw',
    'เนื้อโคหรือเนื้อไก่': 'Beef, flank, separable lean and fat, trimmed to 0" fat, all grades, raw',
    'เนื้อวัว': 'Beef, flank, separable lean and fat, trimmed to 0" fat, all grades, raw',
    'เนื้อวัวสับละเอียด': 'Beef, ground, 80% lean meat / 20% fat, raw',
    'เนื้อเค็มต้ม': 'Beef, cured, corned beef, brisket, raw',
    'เนื้อเค็มทอดฟู': 'Beef, cured, dried',
    'เนื้อสัตว์': 'Beef, flank, separable lean and fat, trimmed to 0" fat, all grades, raw',
    'เนื้อพะแนง': 'Beef, flank, separable lean and fat, trimmed to 0" fat, all grades, raw',
    'ซอสสต็อกเนื้อ': 'Soup, stock, beef, home-prepared',

    'ไก่': 'Chicken, broiler or fryers, meat and skin, raw',
    'เนื้อไก่': 'Chicken, broiler or fryers, meat and skin, raw',
    'อกไก่': 'Chicken, broilers or fryers, breast, meat only, raw',
    'ไก่อ่อน': 'Chicken, broiler or fryers, meat and skin, raw',
    'ไก่อ่อนตัวย่อม': 'Chicken, broiler or fryers, meat and skin, raw',
    'ไก่ครึ่งตัว': 'Chicken, broiler or fryers, meat and skin, raw',
    'ไก่ขนาดกลาง': 'Chicken, broiler or fryers, meat and skin, raw',
    'ไก่นา': 'Chicken, broiler or fryers, meat and skin, raw',
    'เนื้อไก่อ่อน': 'Chicken, broiler or fryers, meat and skin, raw',
    'เนื้อไก่หั่นละเอียด': 'Chicken, ground, raw',
    'เนื้อไก่ต้มสุก': 'Chicken, broiler or fryers, meat and skin, cooked, stewed',
    'เนื้อไก่ต้มซุป': 'Chicken, broiler or fryers, meat and skin, cooked, stewed',
    'น้ำชุบกระดูกไก่': 'Soup, stock, chicken, home-prepared',

    'เป็ดอ่อน': 'Duck, domesticated, meat and skin, raw',
    'นกพิราบ': 'Squab, (pigeon), meat only, raw',
    'นกปากซ่อม สับละเอียด': 'Squab, (pigeon), meat only, raw',

    # --- กลุ่มอาหารทะเล ---
    'กุ้งนาง': 'Crustaceans, shrimp, mixed species, raw',
    'กุ้ง': 'Crustaceans, shrimp, mixed species, raw',
    'กุ้งใหญ่': 'Crustaceans, shrimp, mixed species, raw',
    'เนื้อปู': 'Crustaceans, crab, blue, raw',
    'ปูทะเล': 'Crustaceans, crab, blue, raw',
    'ปูเค็ม': 'Crustaceans, crab, blue, raw',

    'เนื้อปลา': 'Fish, mixed species, raw',
    'ปลา': 'Fish, mixed species, raw',
    'ปลาช่อน': 'Fish, snakehead, raw',
    'ปลาซ่อนย่าง': 'Fish, snakehead, dried',
    'ปลาดุก': 'Fish, catfish, channel, farmed, raw',
    'ปลาทู': 'Fish, mackerel, short, raw',
    'ปลากุเลา': 'Fish, threadfin, raw',
    'ปลาหัวกะโปรง': 'Fish, snapper, mixed species, raw',
    'ปลาคลุมพุก': 'Fish, shad, american, raw',
    'ปลาเกล็ดแข็งอื่นๆ': 'Fish, mixed species, raw',
    'ปลาหางแก้งอย่างดีหรือปลาสลิด': 'Fish, gourami, raw',
    'เนื้อปลาสลาดย่าง': 'Fish, mixed species, dried',
    'ปลาแห้งหรือปลากรอบแกะเนื้อหรือปลาย่างสด': 'Fish, mixed species, dried',
    'ปลาแห้งหรือปลาใบไม้ขนาดกลาง': 'Fish, mixed species, dried',
    'ปลาเค็ม': 'Fish, mackerel, salted',
    'เนื้อปลาเค็ม': 'Fish, mackerel, salted',
    'ปลาเค็มชนิดเนื้อแข็งหั่นชิ้น': 'Fish, mackerel, salted',

    'หอยแมลงภู่': 'Mollusks, mussel, blue, raw',
    'หอยแมลงภู่สด': 'Mollusks, mussel, blue, raw',
    'ปลาหมึกสด': 'Mollusks, squid, mixed species, raw',
    'ปลาหมึกแห้ง': 'Mollusks, squid, mixed species, dried',
    'ไข่แมงดานึ่งสุก': 'Fish, roe, mixed species, cooked, dry heat',
    'ไข่ปลาตะเพียนขนาดใหญ่': 'Fish, roe, mixed species, raw',

    # --- กลุ่มไข่ ---
    'ไข่': 'Egg, whole, raw, fresh',
    'ไข่ไก่': 'Egg, whole, raw, fresh',
    'ไข่เป็ด': 'Egg, duck, whole, fresh',
    'ไข่เค็ม': 'Egg, duck, whole, fresh',
    'ไข่แดง': 'Egg, yolk, raw, fresh',
    'ไข่จืด': 'Egg, whole, raw, fresh',
    'ไข่ต้ม': 'Egg, whole, cooked, hard-boiled',
    'ไข่ต้มสุกแข็ง': 'Egg, whole, cooked, hard-boiled',

    # --- กลุ่มผัก ---
    'กระเทียม': 'Garlic, raw',
    'กระเทียมกลีบใหญ่': 'Garlic, raw',
    'กะเทียม': 'Garlic, raw',
    'หอม': 'Onions, raw',
    'หอมแดง': 'Shallots, raw',
    'หอมซอย': 'Shallots, raw',
    'หอมเล็ก': 'Shallots, raw',
    'หอมหัวเล็ก': 'Shallots, raw',
    'หอมหัวเล็กซอยละเอียด': 'Shallots, raw',
    'หัวหอมเล็กซอย': 'Shallots, raw',
    'หัวหอมเล็ก': 'Shallots, raw',
    'หอมเจียว': 'Shallots, raw',
    'หอมเจียวเล็กน้อย': 'Shallots, raw',
    'หอมเผา': 'Shallots, raw',
    'หัวหอมเผา': 'Shallots, raw',
    'หอมหัวใหญ่': 'Onions, raw',
    'หอมใหญ่': 'Onions, raw',
    'หัวหอม': 'Onions, raw',
    'หัวหอมซอย': 'Onions, raw',
    'หัวหอมกลาง': 'Onions, raw',
    'หัวหอมขนาดกลาง': 'Onions, raw',
    'หัวหอมหั่นสี่เหลี่ยมเล็ก': 'Onions, raw',
    'หอมใหญ่ซอยตามขวาง': 'Onions, raw',
    'หอมใหญ่หั่นเล็ก': 'Onions, raw',
    'หอมใหญ่สับละเอียด': 'Onions, raw',
    'หอมฝรั่งหั่นเล็ก ๆ': 'Onions, raw',
    'หัวหอมปอกแล้วหั่น': 'Onions, raw',
    'หัวหอมสำหรับเจียว': 'Onions, raw',
    'หัวหอมซอยหยาบ ๆ': 'Onions, raw',
    'หัวหอมฝอย': 'Onions, raw',
    'ต้นหอม': 'Onions, spring or scallions (includes tops and bulb), raw',
    'ใบหอม': 'Onions, spring or scallions (includes tops and bulb), raw',

    'รากผักชี': 'Coriander (cilantro) leaves, raw',
    'ผักชี': 'Coriander (cilantro) leaves, raw',
    'ผักซี': 'Coriander (cilantro) leaves, raw',
    'พริกไทย': 'Spices, pepper, black',
    'พริกขี้หนู': 'Peppers, hot chili, green, raw',
    'พริกชี้ฟ้า': 'Peppers, hot chili, red, raw',
    'พริก': 'Peppers, hot chili, red, raw',
    'พริกสด': 'Peppers, hot chili, red, raw',
    'พริกแดง': 'Peppers, hot chili, red, raw',
    'พริกแห้ง': 'Spices, pepper, red or cayenne',
    'พริกป่น': 'Spices, pepper, red or cayenne',
    'พริกสดป่น': 'Spices, pepper, red or cayenne',
    'พริกแห้งป่นละเอียด': 'Spices, pepper, red or cayenne',
    'พริกสวนนอก': 'Peppers, hot chili, green, raw',
    'พริกเหลือง': 'Peppers, hot chili, yellow, raw',
    'พริกเหลืองซอย': 'Peppers, hot chili, yellow, raw',
    'พริกแดงหั่นฝอย': 'Peppers, hot chili, red, raw',
    'พริกแดงหั่นเส้น': 'Peppers, hot chili, red, raw',
    'พริกแดงหั่นบาง': 'Peppers, hot chili, red, raw',
    'พริกหยวกเขียว': 'Peppers, sweet, green, raw',
    'พริกหยวกแดง': 'Peppers, sweet, red, raw',
    'พริกหยวกแดงเขียว': 'Peppers, sweet, red, raw',
    'พริกหยวกอ่อน': 'Peppers, sweet, green, raw',
    'พริกหยวกหั่นเส้น': 'Peppers, sweet, green, raw',
    'พริกสดเขียวหรือแดง': 'Peppers, hot chili, red, raw',
    'พริกแห้งเม็ดใหญ่': 'Spices, pepper, red or cayenne',
    'พริกแห้งเม็ดเล็ก': 'Spices, pepper, red or cayenne',
    'พริกกะเหรี่ยง': 'Peppers, hot chili, red, raw',
    'พริกจินดาแห้ง': 'Spices, pepper, red or cayenne',
    'พริกมูลหนู': 'Peppers, hot chili, red, raw',

    'ขิง': 'Ginger root, raw',
    'ขิงสด': 'Ginger root, raw',
    'ขิงแก่': 'Ginger root, raw',
    'ขิงแก่สด': 'Ginger root, raw',
    'ขิงซอย': 'Ginger root, raw',
    'ขิงหั่นฝอย': 'Ginger root, raw',
    'ขิงหั่นแว่น': 'Ginger root, raw',
    'ขิงสดซอย': 'Ginger root, raw',
    'ขิงสดหั่นฝอย': 'Ginger root, raw',
    'ขิงอ่อนหั่น': 'Ginger root, raw',
    'ขิงอ่อนหั่นฝอย': 'Ginger root, raw',
    'ขิงโขลกคั้นน้ำ': 'Ginger root, raw',
    'ข่า': 'Galangal, raw',
    'ตะไคร้': 'Lemon grass (citronella), raw',
    'มะกรูด': 'Lime leaves, raw',
    'ใบมะกรูด': 'Lime leaves, raw',
    'ใบยี่หร่า': 'Basil, raw',
    'ใบกะเพรา': 'Basil, fresh',
    'ดอกกะเพรา': 'Basil, fresh',
    'ใบโหระพา': 'Basil, fresh',
    'ใบแมงลัก': 'Basil, fresh',
    'ใบสาระแหน่': 'Peppermint, fresh',
    'ใบชะพลู': 'Vegetable, raw',
    'ใบชะพลูทอดกรอบ': 'Vegetable, raw',
    'ใบทองหลางหรือใบขจร/ใบถั่วพลู': 'Vegetable, raw',
    'ดอกโสน': 'Vegetable, raw',
    'ดอกมะขามสด': 'Vegetable, raw',
    'ดอกมะขามหรือใบมะขามอ่อน': 'Vegetable, raw',
    'ใบผักบุ้ง': 'Spinach, raw',
    'ผักบุ้ง': 'Spinach, raw',
    'ผักบุ้งจีน': 'Spinach, raw',
    'ยอดผักบุ้งใหม่': 'Spinach, raw',
    'ผักใบ': 'Spinach, raw',
    'ใบยอ': 'Mustard greens, raw',
    'หัวเปราะ': 'Ginger root, raw',

    'ผักกาดหอม': 'Lettuce, green leaf, raw',
    'ผักกาดหอมจีบ': 'Lettuce, green leaf, raw',
    'ผักกาดหอมล้างสะอาดแช่น้ำด่างทับทิมพอควร': 'Lettuce, green leaf, raw',
    'ใบผักกาดแก้ว': 'Lettuce, iceberg (includes crisphead types), raw',
    'ผักกาดขาว': 'Cabbage, chinese (pe-tsai), raw',
    'กะหล่ำปลี': 'Cabbage, raw',
    'กะหล่ำปลีขนาดเล็ก': 'Cabbage, raw',
    'กล่ำปลีซอย': 'Cabbage, raw',
    'กะหล่ำปลีต้มสับละเอียด': 'Cabbage, cooked, boiled, drained, without salt',
    'คะน้า': 'Kale, raw',
    'ต้นคะน้า': 'Kale, raw',
    'คะน้าต้นใหญ่': 'Kale, raw',
    'ผักคะน้า': 'Kale, raw',
    'คึ่นฉ่าย': 'Celery, raw',
    'ใบคึ่นฉ่าย': 'Celery, raw',
    'ใบคึ่นช่าย': 'Celery, raw',
    'ต้นคึ่นช่าย': 'Celery, raw',
    'ต้นคื่นฉ่าย': 'Celery, raw',
    'ถั่วงอก': 'Bean sprouts, mung, raw',
    'สายบัว': 'Lotus, root, raw',
    'ยอดแค': 'Vegetable, raw',
    'ดอกกุ๊ยช่ายหั่นละเอียดด': 'Chives, raw',
    'ขี้เหล็กต้มคั้นน้ำแล้ว': 'Vegetable, cooked, boiled, drained, without salt',
    'ผักกาดดองหั่น': 'Pickles, vegetable',
    'มะนาว': 'Lime juice, raw',

    'มะเขือเทศ': 'Tomatoes, red, ripe, raw, year round average',
    'มะเขือเทศสุกขนาดกลาง': 'Tomatoes, red, ripe, raw, year round average',
    'มะเขือเทศผลใหญ่': 'Tomatoes, red, ripe, raw, year round average',
    'มะเขือเทศขนาดกลาง': 'Tomatoes, red, ripe, raw, year round average',
    'มะเขือเทศขวด': 'Tomatoes, red, ripe, raw, year round average',
    'มะเขือเปราะ': 'Eggplant, raw',
    'มะเขือยาว': 'Eggplant, raw',
    'มะเขือขาว': 'Eggplant, raw',
    'มะเขืออ่อน': 'Eggplant, raw',
    'มะอึก': 'Eggplant, raw',
    'แตงกวา': 'Cucumber, with peel, raw',
    'แตงร้าน': 'Cucumber, with peel, raw',
    'แตงร้านอ่อน': 'Cucumber, with peel, raw',
    'แตงร้านขนาดกลาง': 'Cucumber, with peel, raw',
    'เปลือกแตงโม': 'Watermelon, raw',
    'ฟัก': 'Waxgourd, (Chinese preserving melon), raw',
    'ฟักเขียว': 'Waxgourd, (Chinese preserving melon), raw',
    'ฟักทอง': 'Pumpkin, raw',
    'ฟักทองหั่น': 'Pumpkin, raw',
    'ฟักทองหั่นแล้ว': 'Pumpkin, raw',
    'ฟักทองปอกเปลือกและหั่นเป็นชิ้น': 'Pumpkin, raw',
    'หน่อไม้': 'Bamboo shoots, raw',
    'หน่อไม้ไผ่ตง': 'Bamboo shoots, raw',
    'หน่อไม้ไผ่ตรง': 'Bamboo shoots, raw',
    'หัวผักกาดแดง': 'Carrots, raw',
    'หัวผักกาดเหลือง': 'Carrots, raw',
    'แครอท': 'Carrots, raw',
    'หัวแครอท': 'Carrots, raw',
    'แครอทหั่นชิ้นพอดีคำ': 'Carrots, raw',
    'หัวผักกาดเค็ม': 'Radish, oriental, dried',
    'หัวผักกาดเค็มหั่นละเอียด': 'Radish, oriental, dried',
    'หัวไชเท้า': 'Radish, oriental, raw',
    'ตั้งฉ่าย': 'Pickles, vegetable',
    'ตังฉ่าย': 'Pickles, vegetable',
    'ตังฉ่ายสับละเอียด': 'Pickles, vegetable',
    'ซีเซ็กฉ่าย': 'Pickles, vegetable',
    'น้ำซีเซ็กฉ่าย': 'Pickles, vegetable',
    'เกี้ยมฉ่ายขนาดกลาง': 'Pickles, vegetable',
    'จีฉ่าย': 'Seaweed, dried',
    'ก๋งฉ่าย': 'Vegetable, raw',
    'มันฝรั่ง': 'Potatoes, flesh and skin, raw',
    'มันฝรั่งหั่นเล็ก ๆ': 'Potatoes, flesh and skin, raw',
    'มันฝรั่งต้มสุกหั่นเล็ก': 'Potatoes, flesh and skin, cooked, boiled, without salt',
    'มันแกว': 'Yambean (jicama), raw',
    'แห้ว': 'Waterchestnuts, chinese, (matai), raw',
    'แห้วจีน': 'Waterchestnuts, chinese, (matai), raw',
    'แห้วหั่นละเอียด': 'Waterchestnuts, chinese, (matai), raw',
    'เห็ดฟาง': 'Mushrooms, straw, canned, drained solids',
    'เห็ดกระป๋องสไลซ์บาง': 'Mushrooms, canned, drained solids',
    'ถั่วฝักยาว': 'Yardlong bean, raw',
    'ถั่วพู': 'Winged bean, raw',
    'ถั่วพูอ่อนหั่นเฉียง': 'Winged bean, raw',
    'ถั่วลันเตา': 'Peas, green, raw',
    'เม็ดถั่วลันเตา': 'Peas, green, raw',
    'ถั่วแขก': 'Beans, snap, green, raw',
    'น้ำเต้า': 'Gourd, white-flowered (calabash), raw',

    # --- กลุ่มผลไม้ ---
    'กล้วย': 'Bananas, raw',
    'กล้วยไข่': 'Bananas, raw',
    'กล้วยน้ำว้าสุก': 'Bananas, raw',
    'ปลีกล้วย': 'Vegetable, raw',
    'มะม่วงดิบ': 'Mango, green, raw',
    'มะม่วงดิบซอย': 'Mango, green, raw',
    'มะละกอ': 'Papayas, raw',
    'สับปะรด': 'Pineapple, raw, all varieties',
    'สับปะรดปอกเปลือก': 'Pineapple, raw, all varieties',
    'มะพร้าว': 'Nuts, coconut meat, raw',
    'มะพร้าวขูด': 'Nuts, coconut meat, raw',
    'มะพร้าวขูดเส้น': 'Nuts, coconut meat, raw',
    'มะพร้าวขูดแล้ว': 'Nuts, coconut meat, raw',
    'มะพร้าวขูดกระต่ายจีน': 'Nuts, coconut meat, raw',
    'มะพร้าวขูดคั่ว': 'Nuts, coconut meat, raw',
    'มะพร้าวคั่ว': 'Nuts, coconut meat, raw',
    'มะพร้าวทึมทึก': 'Nuts, coconut meat, raw',
    'ส้มโอ': 'Pummelo, raw',
    'ส้มเขียวหวาน': 'Tangerines, (mandarin oranges), raw',
    'ส้มซ่า': 'Citron, raw',
    'ผิวส้มเหม็นหั่นละเอียด': 'Lemon peel, raw',
    'เปลือกส้มโอ': 'Pummelo, raw',
    'ส้มมะขามเปียก': 'Tamarind, pulp, raw',
    'น้ำส้มมะขามเปียก': 'Tamarind, pulp, raw',
    'มะขามเปียก': 'Tamarind, pulp, raw',
    'น้ำมะขามเปียก': 'Tamarind, pulp, raw',
    'ระกำฝานแต่เนื้อ': 'Fruit, mixed, raw',
    'มะดัน': 'Lime, raw',
    'มะเฟืองสุก': 'Carambola, (starfruit), raw',
    'ละมุด': 'Sapodilla, raw',
    'พุดชาจีน': 'Jujube, raw',
    'พุทรา': 'Jujube, raw',
    'แอปเปิล': 'Apples, raw, with skin',
    'สาเก': 'Breadfruit, raw',
    'มะตูมอ่อน': 'Fruit, mixed, raw',

    # --- กลุ่มแป้ง ธัญพืช และของแห้ง ---
    'ข้าวเหนียวขาว': 'Rice, white, glutinous, raw',
    'ข้าวสาร': 'Rice, white, raw',
    'ข้าวสาว': 'Rice, white, raw',
    'ข้าวคั่ว': 'Rice, white, raw',
    'ข้าวเบือ': 'Rice, white, glutinous, raw',
    'ข้าวเม่า': 'Rice, white, glutinous, raw',
    'ข้าวตาก': 'Rice, white, raw',
    'แป้งข้าวเจ้า': 'Rice flour, white',
    'แป้งข้าวจ้าว': 'Rice flour, white',
    'แป้งข้าวเจ้าแห้ง': 'Rice flour, white',
    'แป้งข้าวจ้าวแห้ง': 'Rice flour, white',
    'แป้งข้าวแดง': 'Rice flour, white',
    'แป้งข้าวเหนียว': 'Rice flour, glutinous',
    'แป้งข้าวเหนียวขาว': 'Rice flour, glutinous',
    'แป้งสาลี': 'Wheat flour, white, all-purpose, unenriched',
    'แป้งสาลีอเนกประสงค์': 'Wheat flour, white, all-purpose, unenriched',
    'แป้งสาลีอย่างดี': 'Wheat flour, white, cake, enriched',
    'แป้งมัน': 'Cassava starch',
    'แป้งมันสำปะหลัง': 'Cassava starch',
    'แป้งมันอย่างดี': 'Cassava starch',

    'งาขาว': 'Seeds, sesame seeds, whole, dried',
    'งาขาวคั่ว': 'Seeds, sesame seeds, whole, roasted and toasted',
    'งาดำ': 'Seeds, sesame seeds, whole, dried',
    'งาดำคั่วแล้ว': 'Seeds, sesame seeds, whole, dried',
    'เมล็ดแตงโม': 'Seeds, watermelon seed kernels, dried',
    'ถั่วเขียวคั่ว': 'Mung beans, mature seeds, raw',
    'ถั่วทอง': 'Mung beans, mature seeds, sprouted, raw',
    'ถั่วทองคั่วหรือถั่วเขียวคั่ว': 'Mung beans, mature seeds, raw',
    'ถั่วเขียวหรือถั่วทองคั่ว': 'Mung beans, mature seeds, raw',
    'ถั่วเขียว': 'Mung beans, mature seeds, raw',
    'ถั่วเหลือง': 'Soybeans, mature seeds, raw',
    'ถั่วลิสง': 'Peanuts, all types, raw',
    'ถั่วลิสงคั่ว': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วลิสงคั่วป่นละเอียด': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วลิสงคั่วซอย': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วลิสงคั่วซอยแล้ว': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วลิสงดิบ': 'Peanuts, all types, raw',
    'ถั่วลิสงป่น': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วลิสงทอดกรอบ': 'Peanuts, all types, oil-roasted, without salt',
    'ถั่วยี่สงคั่ว': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วยี่สงคั่วใหม่ ๆ': 'Peanuts, all types, dry-roasted, without salt',
    'ถั่วขาวต้มสุก': 'Beans, white, mature seeds, cooked, boiled, without salt',
    'ถั่วกระป๋อง': 'Beans, baked, canned, plain or vegetarian',
    'ถั่วกระป๋องลวก': 'Beans, baked, canned, plain or vegetarian',
    'ถั่วเมล็ดกลม': 'Peas, green, raw',
    'เมล็ดถั่วลันเตาต้มสุกหรือกระป๋อง': 'Peas, green, canned, drained solids',
    'ลูกเกาลัก': 'Chestnuts, chinese, raw',
    'ลูกแปะก๊วย': 'Nuts, ginkgo nuts, raw',
    'ลูกเกดเล็ก': 'Raisins, seeded',

    'วุ้นเส้น': 'Noodles, chinese, cellophane, dry (mung bean)',
    'วุ้นเส้นลวกให้พอง': 'Noodles, chinese, cellophane, dry (mung bean)',
    'วุ้นเคี่ยวแล้วซอย': 'Noodles, chinese, cellophane, dry (mung bean)',
    'เส้นหมี่': 'Rice noodles, dry',
    'เส้นบะหมี่': 'Noodles, egg, dry, enriched',
    'เส้นบะหมี่แห้ง': 'Noodles, egg, dry, enriched',
    'ก๋วยเตี๋ยว': 'Rice noodles, dry',
    'ก๋วยเตี๋ยวเส้นใหญ่': 'Rice noodles, dry',
    'แป้งก๋วยเตี๋ยวที่ยังไม่ได้หั่น': 'Rice noodles, dry',
    'มักกะโรนี': 'Pasta, dry, enriched',
    'สาคูเม็ดเล็ก': 'Tapioca, pearl, dry',
    'ขนมจีน': 'Rice noodles, cooked',
    'ขนมปังสด': 'Bread, white, commercially prepared',
    'ขนมปังแห้ง': 'Bread, white, commercially prepared',
    'ขนมปังป่นหยาบ': 'Bread, crumbs, dry, grated, plain',
    'ข้าวคั่วหรือผงขนมปัง': 'Bread, crumbs, dry, grated, plain',
    'เกล็ดขนมปัง': 'Bread, crumbs, dry, grated, plain',
    'เต้าหู้': 'Tofu, raw, regular, prepared with calcium sulfate',
    'เต้าหู้เหลือง': 'Tofu, raw, regular, prepared with calcium sulfate',
    'เต้าหู้เหลืองอย่างอ่อน': 'Tofu, soft, prepared with calcium sulfate',
    'เต้าหู่ยี้อย่างดี': 'Tofu, fermented',
    'เต้าหู้ยี้': 'Tofu, fermented',

    # --- กลุ่มเครื่องปรุง ---
    'น้ำปลา': 'Fish sauce',
    'น้ำเคยดี': 'Shrimp paste',
    'น้ำเคย': 'Shrimp paste',
    'กะปิ': 'Shrimp paste',
    'น้ำพริกก้อย': 'Shrimp paste',
    'น้ำพริกเผา': 'Sauce, chili, commercially prepared',
    'เครื่องแกงเผ็ด': 'Sauce, curry, red, ready-to-serve',
    'เครื่องพะโล้': 'Spices, five-spice powder',
    'ผงกะหรี่': 'Spices, curry powder',
    'ผงชูรส': 'NOT_FOUND_MSG',
    'ผงซูรส': 'NOT_FOUND_MSG',
    'ผงปรุงรส': 'Soup, stock, chicken, home-prepared',
    'ซีอิ๊ว': 'Soy sauce made from soy and wheat (shoyu)',
    'ซีอิ๊วขาว': 'Soy sauce made from soy and wheat (shoyu)',
    'ซีอิ๊วใส': 'Soy sauce made from soy and wheat (shoyu)',
    'ซีอิ๊วเค็ม': 'Soy sauce made from soy and wheat (shoyu)',
    'ซี้อิ๊วขาว': 'Soy sauce made from soy and wheat (shoyu)',
    'น้ำซีอิ๊ว': 'Soy sauce made from soy and wheat (shoyu)',
    'ซีอิ้วขาว': 'Soy sauce made from soy and wheat (shoyu)',
    'ซีอิ้วดำ': 'Sauce, hoisin, ready-to-serve',
    'ซีอิ๊วดำ': 'Sauce, hoisin, ready-to-serve',
    'เต้าเจี้ยว': 'Miso',
    'เต้าเจี้ยวน้ำ': 'Miso',
    'ซอสปรุงรส': 'Sauce, soy, unspecified',
    'ซอสฝาเขียว': 'Sauce, soy, unspecified',
    'แม็กกี้': 'Sauce, soy, unspecified',
    'ซอสศรีราชา': 'Sauce, hot chile, sriracha',
    'ซอสมะเขือเทศ': 'Catsup',
    'ซอสกระต่าย': 'Catsup',
    'น้ำมันหอย': 'Sauce, oyster, ready-to-serve',
    'น้ำมัน': 'Oil, vegetable, unspecified',
    'น้ำมันงา': 'Oil, sesame, salad or cooking',
    'น้ำมันรำ': 'Oil, rice bran',
    'น้ำมันรำข้าว': 'Oil, rice bran',
    'น้ำมันสำหรับทอด': 'Oil, vegetable, unspecified',
    'น้ำมันพืช': 'Oil, vegetable, unspecified',
    'เนย': 'Butter, salted',
    'เนยสด': 'Butter, salted',
    'เนยละลาย': 'Butter, salted',
    'เนยสำหรับทาภาชนะ': 'Butter, salted',
    'เนยแข็งป่น': 'Cheese, cheddar',
    'เนยแข็ง': 'Cheese, cheddar',
    'กะทิ': 'Nuts, coconut milk, raw (liquid expressed from grated meat and water)',
    'หัวกะทิ': 'Nuts, coconut cream, raw (liquid expressed from grated meat)',
    'น้ำตาล': 'Sugars, granulated',
    'น้ำตาลทราย': 'Sugars, granulated',
    'น้ำตาลปึก': 'Sugars, palm',
    'น้ำตาลปีบ': 'Sugars, palm',
    'น้ำตาลหม้อ': 'Sugars, palm',
    'น้ำตาลมะพร้าว': 'Sugars, palm',
    'น้ำตาลโตนด': 'Sugars, palm',
    'น้ำตาลมะพร้าว หรือ น้ำตาลโตนด': 'Sugars, palm',
    'น้ำตาลมะพร้าวหรือน้ำตาลตะโหนด': 'Sugars, palm',
    'น้ำเชื่อม': 'Syrups, table blends, pancake',
    'น้ำผึ้ง': 'Honey',
    'น้ำส้ม': 'Vinegar, distilled',
    'น้ำส้มสายชู': 'Vinegar, distilled',
    'เกลือ': 'Salt, table',
    'เกลือป่น': 'Salt, table',
    'ผงฟู': 'Leavening agents, baking powder, double-acting, sodium aluminum sulfate',
    'ดินประสิว': 'Preservatives',

    # --- กลุ่มเครื่องเทศ ---
    'อบเชย': 'Spices, cinnamon, ground',
    'อบเชย ประมาณ': 'Spices, cinnamon, ground',
    'อบเชยเล็ก': 'Spices, cinnamon, ground',
    'โป๊ยกั๊ก': 'Spices, anise seed',
    'ลูกโป๊ยกั๊ก': 'Spices, anise seed',
    'กานพลู': 'Spices, cloves',
    'กระวาน': 'Spices, cardamom',
    'กะวาน': 'Spices, cardamom',
    'ใบกระวาน': 'Spices, bay leaf',
    'ลูกจันทร์': 'Spices, nutmeg, ground',
    'ลูกจันทร์ป่น': 'Spices, nutmeg, ground',
    'ดอกจันทร์': 'Spices, mace, ground',
    'ผงลูกจันทร์เทศ': 'Spices, nutmeg, ground',
    'ดีปลี': 'Spices, pepper, black',
    'ขมิ้น': 'Spices, turmeric, ground',
    'ขมิ้นผง': 'Spices, turmeric, ground',
    'ขมิ้นแห้ง': 'Spices, turmeric, ground',
    'ขมิ้นแขก': 'Spices, turmeric, ground',
    'ขมิ้นขาวหั่น': 'Spices, turmeric, ground',
    'ขมิ้นขาวหั่นแฉลบบาง ๆ': 'Spices, turmeric, ground',
    'ไพล': 'Spices, turmeric, ground',
    'กระชาย': 'Ginger root, raw',
    'กระชายหั่น': 'Ginger root, raw',
    'กะชาย': 'Ginger root, raw',
    'กะชายมีหัวติด': 'Ginger root, raw',
    'ยี่หร่า': 'Spices, cumin seed',
    'ลูกจันทน์ป่น': 'Spices, nutmeg, ground',

    # --- อื่นๆ ---
    'นมสด': 'Milk, whole, 3.25% milkfat, with added vitamin D',
    'นมอุ่น': 'Milk, whole, 3.25% milkfat, with added vitamin D',
    'โกโก้': 'Cocoa, dry powder, unsweetened',
    'น้ำ': 'Water, bottled, generic',
    'น้ำเปล่า': 'Water, bottled, generic',
    'น้ำสะอาด': 'Water, bottled, generic',
    'น้ำเย็น': 'Water, bottled, generic',
    'น้ำร้อน': 'Water, bottled, generic',
    'น้ำเปล่าหรือน้ำข้าวต้ม': 'Water, bottled, generic',
    'น้ำสำหรับนวดแป้ง': 'Water, bottled, generic',
    'น้ำลอยดอกไม้': 'Water, bottled, generic',
    'น้ำดอกไม้สด': 'Water, bottled, generic',
    'น้ำปูนใส': 'Water, bottled, generic',
    'น้ำข้าวหมาก': 'Alcoholic beverage, rice (sake)',
    'เหล้า': 'Alcoholic beverage, rice (sake)',
    'เหล้าจีน': 'Alcoholic beverage, rice (sake)',
    'เหล้าเสียว': 'Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof',
    'เหล้าบรั่นดี': 'Alcoholic beverage, distilled, brandy',
    'น้ำแกงดี': 'Soup, stock, chicken, home-prepared',
    'น้ำหรือน้ำซุป': 'Soup, stock, chicken, home-prepared',
    'น้ำชุบกระดูกไก่': 'Soup, stock, chicken, home-prepared',
    'น้ำผลไม้': 'Fruit juice, mixed',
    'น้ำมะเขือเทศ': 'Tomato juice, canned, without salt',
    'น้ำวานิลลา': 'Vanilla extract',
    'กลิ่นวานิลลา': 'Vanilla extract',
    'น้ำหอมหรือสีตามชอบเล็กน้อย': 'Water, bottled, generic',
    'ใบตอง': 'Water, bottled, generic',
    'ใบตองสำหรับห่อ': 'Water, bottled, generic',
    'ใบตองสำหรับปิ้ง': 'Water, bottled, generic',
    'ใบตองสำหรับรอง': 'Water, bottled, generic',
    'กาบมะพร้าวเผาไฟป่นละเอียด': 'Water, bottled, generic',
    'ไม้กลัด': 'Water, bottled, generic',
    'ดินสอพอง': 'Water, bottled, generic',
    'ใบเมี่ยง': 'Water, bottled, generic',
    'ผักสดสำหรับรับประทาน': 'Vegetable, raw',
    'กระยาสารท': 'NOT_FOUND_COMPLEX_DISH',
    'ดอกมะลิ กะดังงา เทียนอบ': 'Water, bottled, generic'
}